boatapp/urls.py
from django.urls import path

from boatapp.apps import BoatappConfig
from boatapp.views import BoatListView, BoatDetailView

app_name = BoatappConfig.name

urlpatterns = [
    path('', BoatListView.as_view(), name='boat_list'),  # путь к списку лодок
    path('<int:pk>/', BoatDetailView.as_view(), name='boat_view'),  # путь к карточке лодки
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('boatapp.urls', namespace='boatapp')),
    path('order/', include('orderapp.urls', namespace='orderapp')),
]

orderapp/urls.py
from django.urls import path

from orderapp.apps import OrderappConfig
from orderapp.views import OrderCreateView

app_name = OrderappConfig.name

urlpatterns = [
    path('create/<int:pk>/', OrderCreateView.as_view(), name='create'),
]

boatapp/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Owner(models.Model):
    """Модель владельца"""
    name = models.CharField(max_length=100, verbose_name='имя')
    email = models.EmailField(max_length=100, verbose_name='почта', unique=True)

    def __str__(self):
        return f'{self.email} ({self.name})'

    class Meta:
        verbose_name = 'владелец'
        verbose_name_plural = 'владельцы'


class Boat(models.Model):
    """Модель лодка"""
    name = models.CharField(max_length=100, verbose_name='название')
    year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name='год выпуска')
    price = models.IntegerField(**NULLABLE, verbose_name='цена')

    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, verbose_name='владелец')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'лодка'
        verbose_name_plural = 'лодки'

class BoatHistory(models.Model):
    """Модель истории лодки"""
    boat = models.ForeignKey(Boat, on_delete=models.CASCADE, verbose_name='лодка')

    owner = models.ForeignKey(Owner, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)

    start_year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name='владел с ')
    stop_year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name='владел по ')

    def __str__(self):
        return f'{self.boat} {self.start_year} - {self.stop_year}'

    class Meta:
        verbose_name = 'история лодки'
        verbose_name_plural = 'истории лодок'

orderapp/models.py
from django.db import models

# Create your models here.
class Order(models.Model):
    """Модель заказа"""
    boat = models.ForeignKey('boatapp.Boat', on_delete=models.CASCADE, verbose_name='лодка')

    name = models.CharField(max_length=100, verbose_name='название заказа')
    email = models.EmailField(max_length=150, verbose_name='почта')
    message = models.TextField(verbose_name='сообщение')

    closed = models.BooleanField(default=False, verbose_name='заказ закрыт')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='время создания')

    def __str__(self):
        return f'{self.boat} от {self.email}'

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

boatapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from boatapp.models import Boat


class BoatListView(ListView):
    """Контроллер списка лодок"""
    model = Boat

class BoatDetailView(DetailView):
    """Контроллер подробной информации о лодке"""
    model = Boat

orderapp/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.urls import reverse

from boatapp.models import Boat
from orderapp.models import Order
from orderapp.services import send_order_email


# Create your views here.
class OrderCreateView(CreateView):
    """Контроллер для создания заказа"""
    model = Order
    fields = ('boat', 'name', 'email', 'message',)

    def get_success_url(self):
        """Возвращает путь к странице создания заказа"""
        return reverse('boatapp:boat_view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        """Возвращает контекст данных"""
        context_data = super(OrderCreateView, self).get_context_data(**kwargs)
        context_data['boat'] = get_object_or_404(Boat, pk=self.kwargs.get('pk'))
        return context_data

    def form_valid(self, form):
        """Метод для обработки формы отправки письма"""
        obj = form.save()
        send_order_email(obj)
        return super().form_valid(form)

boatapp/templates/boatapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% if title %}{{ title }} - {% endif %}Продажа лодок</title>




    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>
  <body>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>

<div class="container py-3">
  <header>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">Продажа лодок</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'boatapp:boat_list' %}">Лодки</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="#">Enterprise</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="#">Support</a>
        <a class="py-2 text-dark text-decoration-none" href="#">Pricing</a>
      </nav>
    </div>

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">{{ title }}</h1>
    </div>
  </header>

  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% block content %}
        {% endblock %}

    </div>

  </main>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="24" height="19">
        <small class="d-block mb-3 text-muted">&copy; 2017–2021</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Team</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>



  </body>
</html>

boatapp/templates/boatapp/boat_detail.html
{% extends 'boatapp/base.html' %}

{% block content %}
            <div class="card">
                <div class="card-header">{{ object.name }}</div>
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <th>Начало</th>
                            <th>Окончание</th>
                            <th>Владелец</th>
                        </tr>
                        {% for history_item in object.boathistory_set.all %}
                            <tr>
                                <td>{{ history_item.start_year }}</td>
                                <td>
                                    {% if history_item.stop_year %}
                                        {{ history_item.stop_year }}
                                    {% else %}
                                        по настоящее время
                                    {% endif %}
                                </td>
                                <td>
                                    {% if history_item.owner %}
                                        {{ history_item.owner }}
                                    {% else %}
                                        Не указан
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>

                </div>
                <div class="card-footer">
                    <a href="{% url 'orderapp:create' object.pk %}" class="btn btn-outline-success">Оставить заявку</a>
                </div>
            </div>
{% endblock %}

boatapp/templates/boatapp/boat_list.html
{% extends 'boatapp/base.html' %}

{% block content %}
 <!-- список лодок -->

    {% for object in object_list %}

        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                {% if object.price %}
                    <h2 class="card-title pricing-card-title">{{ object.price }} руб.</h2>
                {% else %}
                    <h2 class="card-title pricing-card-title">
                        <small class="text-muted">не указана</small>
                    </h2>

                {% endif %}
                 <!-- кнопка Информация-->
                <a href="{% url 'boatapp:boat_view' object.pk %}" type="button" class="w-100 btn btn-lg btn-outline-primary">
                    Информация
                </a>
            </div>
        </div>

    {% endfor %}
{#      <div class="col">#}
{#        <div class="card mb-4 rounded-3 shadow-sm">#}
{#          <div class="card-header py-3">#}
{#            <h4 class="my-0 fw-normal">Pro</h4>#}
{#          </div>#}
{#          <div class="card-body">#}
{#            <h1 class="card-title pricing-card-title">$15<small class="text-muted fw-light">/mo</small></h1>#}
{#            <ul class="list-unstyled mt-3 mb-4">#}
{#              <li>20 users included</li>#}
{#              <li>10 GB of storage</li>#}
{#              <li>Priority email support</li>#}
{#              <li>Help center access</li>#}
{#            </ul>#}
{#            <button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#      <div class="col">#}
{#        <div class="card mb-4 rounded-3 shadow-sm border-primary">#}
{#          <div class="card-header py-3 text-white bg-primary border-primary">#}
{#            <h4 class="my-0 fw-normal">Enterprise</h4>#}
{#          </div>#}
{#          <div class="card-body">#}
{#            <h1 class="card-title pricing-card-title">$29<small class="text-muted fw-light">/mo</small></h1>#}
{#            <ul class="list-unstyled mt-3 mb-4">#}
{#              <li>30 users included</li>#}
{#              <li>15 GB of storage</li>#}
{#              <li>Phone and email support</li>#}
{#              <li>Help center access</li>#}
{#            </ul>#}
{#            <button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}

{% endblock %}

orderapp/templates/orderapp/order_form.html
{% extends 'boatapp/base.html' %}


{% block content %}
            <div class="card">
                <div class="card-header">Создание заявки на лодку {{ boat }}</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="boat_id" value="{{ boat.pk }}">
                        {{ form.as_p }}
                        <button type='submit' class="btn btn-success">Оставить заявку</button>
                    </form>

                </div>

            </div>
{% endblock %}